language: java

install: ant deps-tests

script:
  ant test

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: oraclejdk10
    - jdk: oraclejdk12
    - jdk: openjdk-ea
